Repository MicahWW/Python-Games, pull requests merged in 2023-02, with the labels that each got.

#56 Just some formatting cleanup!
  TicTacToe.py
Labels: documentation, enhancement

#57 Fix string input
  main.py
Labels: bug

#58 Fixed main
  main.py
Labels: invalid

#60 Terminal game own class
  TicTacToe.py
  main.py
  test_TicTacToe.py
Labels: enhancement

#65 New bot strategy
  TicTacToe.py
Labels: enhancement

#69 Documentation update!
  TicTacToe.py
  test_TicTacToe.py
Labels: documentation

#72 PyTest checks bot in complex scenarios
  test_TicTacToe.py
Labels: enhancement, testing

#73 Block double-middle strategy
  TicTacToe.py
  test_TicTacToe.py
Labels: enhancement
